const VERB_DATA = {
    irregular: [
        { id: 1, infinitive: "Be (am/is/are)", past: "Was / Were", participle: "Been", pastContinuous: "Being", spanish: "Ser / Estar" },
        { id: 2, infinitive: "Become", past: "Became", participle: "Become", pastContinuous: "Becoming", spanish: "Llegar a Ser" },
        { id: 3, infinitive: "Begin", past: "Began", participle: "Begun", pastContinuous: "Beginning", spanish: "Empezar" },
        { id: 4, infinitive: "Break", past: "Broke", participle: "Broken", pastContinuous: "Breaking", spanish: "Romper" },
        { id: 5, infinitive: "Bring", past: "Brought", participle: "Brought", pastContinuous: "Bringing", spanish: "Traer / Llevar" },
        { id: 6, infinitive: "Build", past: "Built", participle: "Built", pastContinuous: "Building", spanish: "Edificar" },
        { id: 7, infinitive: "Buy", past: "Bought", participle: "Bought", pastContinuous: "Buying", spanish: "Comprar" },
        { id: 8, infinitive: "Come", past: "Came", participle: "Come", pastContinuous: "Coming", spanish: "Venir" },
        { id: 9, infinitive: "Cost", past: "Cost", participle: "Cost", pastContinuous: "Costing", spanish: "Costar" },
        { id: 10, infinitive: "Cut", past: "Cut", participle: "Cut", pastContinuous: "Cutting", spanish: "Cortar" },
        { id: 11, infinitive: "Choose", past: "Chose", participle: "Chosen", pastContinuous: "Choosing", spanish: "Elegir" },
        { id: 12, infinitive: "Do", past: "Did", participle: "Done", pastContinuous: "Doing", spanish: "Hacer" },
        { id: 13, infinitive: "Draw", past: "Drew", participle: "Drawn", pastContinuous: "Drawing", spanish: "Dibujar" },
        { id: 14, infinitive: "Drink", past: "Drank", participle: "Drunk", pastContinuous: "Drinking", spanish: "Beber" },
        { id: 15, infinitive: "Drive", past: "Drove", participle: "Driven", pastContinuous: "Driving", spanish: "Conducir" },
        { id: 16, infinitive: "Eat", past: "Ate", participle: "Eaten", pastContinuous: "Eating", spanish: "Comer" },
        { id: 17, infinitive: "Fall", past: "Fell", participle: "Fallen", pastContinuous: "Falling", spanish: "Caer" },
        { id: 18, infinitive: "Feel", past: "Felt", participle: "Felt", pastContinuous: "Feeling", spanish: "Sentir" },
        { id: 19, infinitive: "Fight", past: "Fought", participle: "Fought", pastContinuous: "Fighting", spanish: "Luchar" },
        { id: 20, infinitive: "Find", past: "Found", participle: "Found", pastContinuous: "Finding", spanish: "Encontrar" },
        { id: 21, infinitive: "Fly", past: "Flew", participle: "Flown", pastContinuous: "Flying", spanish: "Volar" },
        { id: 22, infinitive: "Forget", past: "Forgot", participle: "Forgotten", pastContinuous: "Forgetting", spanish: "Olvidar" },
        { id: 23, infinitive: "Forgive", past: "Forgave", participle: "Forgiven", pastContinuous: "Forgiving", spanish: "Perdonar" },
        { id: 24, infinitive: "Get", past: "Got", participle: "Got / Gotten", pastContinuous: "Getting", spanish: "Obtener" },
        { id: 25, infinitive: "Give", past: "Gave", participle: "Given", pastContinuous: "Giving", spanish: "Dar" },
        { id: 26, infinitive: "Go", past: "Went", participle: "Gone", pastContinuous: "Going", spanish: "Ir" },
        { id: 27, infinitive: "Grow", past: "Grew", participle: "Grown", pastContinuous: "Growing", spanish: "Crecer" },
        { id: 28, infinitive: "Have", past: "Had", participle: "Had", pastContinuous: "Having", spanish: "Haber o Tener" },
        { id: 29, infinitive: "Hear", past: "Heard", participle: "Heard", pastContinuous: "Hearing", spanish: "Oír" },
        { id: 30, infinitive: "Know", past: "Knew", participle: "Known", pastContinuous: "Knowing", spanish: "Saber / Conocer" },
        { id: 31, infinitive: "Learn", past: "Learnt / Learned", participle: "Learnt / Learned", pastContinuous: "Learning", spanish: "Aprender" },
        { id: 32, infinitive: "Lend", past: "Lent", participle: "Lent", pastContinuous: "Lending", spanish: "Prestar" },
        { id: 33, infinitive: "Make", past: "Made", participle: "Made", pastContinuous: "Making", spanish: "Hacer" },
        { id: 34, infinitive: "Meet", past: "Met", participle: "Met", pastContinuous: "Meeting", spanish: "Encontrar" },
        { id: 35, infinitive: "Pay", past: "Paid", participle: "Paid", pastContinuous: "Paying", spanish: "Pagar" },
        { id: 36, infinitive: "Put", past: "Put", participle: "Put", pastContinuous: "Putting", spanish: "Poner" },
        { id: 37, infinitive: "Read", past: "Read", participle: "Read", pastContinuous: "Reading", spanish: "Leer" },
        { id: 38, infinitive: "Ride", past: "Rode", participle: "Ridden", pastContinuous: "Riding", spanish: "Montar" },
        { id: 39, infinitive: "Run", past: "Ran", participle: "Run", pastContinuous: "Running", spanish: "Correr" },
        { id: 40, infinitive: "Say", past: "Said", participle: "Said", pastContinuous: "Saying", spanish: "Decir" },
        { id: 41, infinitive: "See", past: "Saw", participle: "Seen", pastContinuous: "Seeing", spanish: "Ver" },
        { id: 42, infinitive: "Sell", past: "Sold", participle: "Sold", pastContinuous: "Selling", spanish: "Vender" },
        { id: 43, infinitive: "Send", past: "Sent", participle: "Sent", pastContinuous: "Sending", spanish: "Enviar" },
        { id: 44, infinitive: "Sing", past: "Sang", participle: "Sung", pastContinuous: "Singing", spanish: "Cantar" },
        { id: 45, infinitive: "Sit", past: "Sat", participle: "Sat", pastContinuous: "Sitting", spanish: "Sentarse" },
        { id: 46, infinitive: "Sleep", past: "Slept", participle: "Slept", pastContinuous: "Sleeping", spanish: "Dormir" },
        { id: 47, infinitive: "Speak", past: "Spoke", participle: "Spoken", pastContinuous: "Speaking", spanish: "Hablar" },
        { id: 48, infinitive: "Spell", past: "Spelt", participle: "Spelt", pastContinuous: "Spelling", spanish: "Deletrear" },
        { id: 49, infinitive: "Spend", past: "Spent", participle: "Spent", pastContinuous: "Spending", spanish: "Gastar" },
        { id: 50, infinitive: "Steal", past: "Stole", participle: "Stolen", pastContinuous: "Stealing", spanish: "Robar" },
        { id: 51, infinitive: "Swim", past: "Swam", participle: "Swum", pastContinuous: "Swimming", spanish: "Nadar" },
        { id: 52, infinitive: "Take", past: "Took", participle: "Taken", pastContinuous: "Taking", spanish: "Coger" },
        { id: 53, infinitive: "Teach", past: "Taught", participle: "Taught", pastContinuous: "Teaching", spanish: "Enseñar" },
        { id: 54, infinitive: "Tell", past: "Told", participle: "Told", pastContinuous: "Telling", spanish: "Decir" },
        { id: 55, infinitive: "Think", past: "Thought", participle: "Thought", pastContinuous: "Thinking", spanish: "Pensar" },
        { id: 56, infinitive: "Throw", past: "Threw", participle: "Thrown", pastContinuous: "Throwing", spanish: "Arrojar / Tirar" },
        { id: 57, infinitive: "Understand", past: "Understood", participle: "Understood", pastContinuous: "Understanding", spanish: "Entender" },
        { id: 58, infinitive: "Wake", past: "Woke", participle: "Woken", pastContinuous: "Waking", spanish: "Despertarse" },
        { id: 59, infinitive: "Wear", past: "Wore", participle: "Worn", pastContinuous: "Wearing", spanish: "Llevar puesto" },
        { id: 60, infinitive: "Write", past: "Wrote", participle: "Written", pastContinuous: "Writing", spanish: "Escribir" }
    ],
    regularId: [
        { id: 1, infinitive: "Accept", past: "Accepted /id/", participle: "Accepted /id/", pastContinuous: "Accepting", spanish: "Aceptar" },
        { id: 2, infinitive: "Count", past: "Counted /id/", participle: "Counted /id/", pastContinuous: "Counting", spanish: "Contar" },
        { id: 3, infinitive: "End", past: "Ended /id/", participle: "Ended /id/", pastContinuous: "Ending", spanish: "Terminar" },
        { id: 4, infinitive: "Expect", past: "Expected /id/", participle: "Expected /id/", pastContinuous: "Expecting", spanish: "Esperar" },
        { id: 5, infinitive: "Intend", past: "Intended /id/", participle: "Intended /id/", pastContinuous: "Intending", spanish: "Intentar" },
        { id: 6, infinitive: "Need", past: "Needed /id/", participle: "Needed /id/", pastContinuous: "Needing", spanish: "Necesitar" },
        { id: 7, infinitive: "Plant", past: "Planted /id/", participle: "Planted /id/", pastContinuous: "Planting", spanish: "Plantar" },
        { id: 8, infinitive: "Point", past: "Pointed /id/", participle: "Pointed /id/", pastContinuous: "Pointing", spanish: "Señalar" },
        { id: 9, infinitive: "Rent", past: "Rented /id/", participle: "Rented /id/", pastContinuous: "Renting", spanish: "Rentar" },
        { id: 10, infinitive: "Repeat", past: "Repeated /id/", participle: "Repeated /id/", pastContinuous: "Repeating", spanish: "Repetir" },
        { id: 11, infinitive: "Resist", past: "Resisted /id/", participle: "Resisted /id/", pastContinuous: "Resisting", spanish: "Resistir" },
        { id: 12, infinitive: "Start", past: "Started /id/", participle: "Started /id/", pastContinuous: "Starting", spanish: "Empezar" },
        { id: 13, infinitive: "Visit", past: "Visited /id/", participle: "Visited /id/", pastContinuous: "Visiting", spanish: "Visitar" },
        { id: 14, infinitive: "Wait", past: "Waited /id/", participle: "Waited /id/", pastContinuous: "Waiting", spanish: "Esperar" },
        { id: 15, infinitive: "Want", past: "Wanted /id/", participle: "Wanted /id/", pastContinuous: "Wanting", spanish: "Querer" }
    ],
    regularT: [
        { id: 1, infinitive: "Ask", past: "Asked /t/", participle: "Asked /t/", pastContinuous: "Asking", spanish: "Preguntar" },
        { id: 2, infinitive: "Cook", past: "Cooked /t/", participle: "Cooked /t/", pastContinuous: "Cooking", spanish: "Cocinar" },
        { id: 3, infinitive: "Dance", past: "Danced /t/", participle: "Danced /t/", pastContinuous: "Dancing", spanish: "Bailar" },
        { id: 4, infinitive: "Erase", past: "Erased /t/", participle: "Erased /t/", pastContinuous: "Erasing", spanish: "Borrar" },
        { id: 5, infinitive: "Finish", past: "Finished /t/", participle: "Finished /t/", pastContinuous: "Finishing", spanish: "Terminar" },
        { id: 6, infinitive: "Help", past: "Helped /t/", participle: "Helped /t/", pastContinuous: "Helping", spanish: "Ayudar" },
        { id: 7, infinitive: "Like", past: "Liked /t/", participle: "Liked /t/", pastContinuous: "Liking", spanish: "Gustar" },
        { id: 8, infinitive: "Look", past: "Looked /t/", participle: "Looked /t/", pastContinuous: "Looking", spanish: "Mirar" },
        { id: 9, infinitive: "Practice", past: "Practiced /t/", participle: "Practiced /t/", pastContinuous: "Practicing", spanish: "Practicar" },
        { id: 10, infinitive: "Stop", past: "Stopped /t/", participle: "Stopped /t/", pastContinuous: "Stopping", spanish: "Detener" },
        { id: 11, infinitive: "Talk", past: "Talked /t/", participle: "Talked /t/", pastContinuous: "Talking", spanish: "Hablar" },
        { id: 12, infinitive: "Use", past: "Used /t/", participle: "Used /t/", pastContinuous: "Using", spanish: "Usar" },
        { id: 13, infinitive: "Walk", past: "Walked /t/", participle: "Walked /t/", pastContinuous: "Walking", spanish: "Caminar" },
        { id: 14, infinitive: "Wash", past: "Washed /t/", participle: "Washed /t/", pastContinuous: "Washing", spanish: "Lavar" },
        { id: 15, infinitive: "Work", past: "Worked /t/", participle: "Worked /t/", pastContinuous: "Working", spanish: "Trabajar" }
    ],
    regularD: [
        { id: 1, infinitive: "Answer", past: "Answered /d/", participle: "Answered /d/", pastContinuous: "answering", spanish: "Responder" },
        { id: 2, infinitive: "Arrive", past: "Arrived /d/", participle: "Arrived /d/", pastContinuous: "Arriving", spanish: "Llegar / Arribar" },
        { id: 3, infinitive: "Belong", past: "Belonged /d/", participle: "Belonged /d/", pastContinuous: "Belonging", spanish: "Pertenecer" },
        { id: 4, infinitive: "Change", past: "Changed /d/", participle: "Changed /d/", pastContinuous: "Changing", spanish: "Cambiar" },
        { id: 5, infinitive: "Clean", past: "Cleaned /d/", participle: "Cleaned /d/", pastContinuous: "Cleaning", spanish: "Limpiar" },
        { id: 6, infinitive: "Climb", past: "Climbed /d/", participle: "Climbed /d/", pastContinuous: "Climbing", spanish: "Escalar" },
        { id: 7, infinitive: "Close", past: "Closed /d/", participle: "Closed /d/", pastContinuous: "Closing", spanish: "Cerrar" },
        { id: 8, infinitive: "Consider", past: "Considered /d/", participle: "Considered /d/", pastContinuous: "Considering", spanish: "Considerar" },
        { id: 9, infinitive: "Deliver", past: "Delivered /d/", participle: "Delivered /d/", pastContinuous: "Delivering", spanish: "Entregar" },
        { id: 10, infinitive: "Enjoy", past: "Enjoyed /d/", participle: "Enjoyed /d/", pastContinuous: "Enjoying", spanish: "Disfrutar" },
        { id: 11, infinitive: "Fill", past: "Filled /d/", participle: "Filled /d/", pastContinuous: "Filling", spanish: "Llenar" },
        { id: 12, infinitive: "Follow", past: "Followed /d/", participle: "Followed /d/", pastContinuous: "Following", spanish: "Seguir" },
        { id: 13, infinitive: "Hurry", past: "Hurried /d/", participle: "Hurried /d/", pastContinuous: "Hurrying", spanish: "Darse prisa" },
        { id: 14, infinitive: "Learn", past: "Learned /d/", participle: "Learned /d/", pastContinuous: "Learning", spanish: "Aprender" },
        { id: 15, infinitive: "Listen", past: "Listened /d/", participle: "Listened /d/", pastContinuous: "Listening", spanish: "Escuchar" },
        { id: 16, infinitive: "Live", past: "Lived /d/", participle: "Lived /d/", pastContinuous: "Living", spanish: "Vivir" },
        { id: 17, infinitive: "Love", past: "Loved /d/", participle: "Loved /d/", pastContinuous: "Loving", spanish: "Amar" },
        { id: 18, infinitive: "Name", past: "Named /d/", participle: "Named /d/", pastContinuous: "Naming", spanish: "Nombrar" },
        { id: 19, infinitive: "Open", past: "Opened /d/", participle: "Opened /d/", pastContinuous: "Opening", spanish: "Abrir" },
        { id: 20, infinitive: "Order", past: "Ordered /d/", participle: "Ordered /d/", pastContinuous: "Ordering", spanish: "Ordenar" },
        { id: 21, infinitive: "Plan", past: "Planed /d/", participle: "Planed /d/", pastContinuous: "Planning", spanish: "Planear" },
        { id: 22, infinitive: "Play", past: "Played /d/", participle: "Played /d/", pastContinuous: "Playing", spanish: "Jugar" },
        { id: 23, infinitive: "Rain", past: "Rained /d/", participle: "Rained /d/", pastContinuous: "Raining", spanish: "Llover" },
        { id: 24, infinitive: "Remember", past: "Remembered /d/", participle: "Remembered /d/", pastContinuous: "Remembering", spanish: "Recordar" },
        { id: 25, infinitive: "Show", past: "Showed /d/", participle: "Showed /d/", pastContinuous: "Showing", spanish: "Mostrar" },
        { id: 26, infinitive: "Stay", past: "Stayed /d/", participle: "Stayed /d/", pastContinuous: "Staying", spanish: "Permanecer" },
        { id: 27, infinitive: "Study", past: "Studied /d/", participle: "Studied /d/", pastContinuous: "Studying", spanish: "Estudiar" },
        { id: 28, infinitive: "Travel", past: "Traveled /d/", participle: "Traveled /d/", pastContinuous: "Traveling", spanish: "Viajar" },
        { id: 29, infinitive: "Try", past: "Tried /d/", participle: "Tried /d/", pastContinuous: "Trying", spanish: "Intentar / Tratar" },
        { id: 30, infinitive: "Turn", past: "Turned /d/", participle: "Turned /d/", pastContinuous: "Turning", spanish: "Voltear / Dar vuelta" }
    ]
};
